import React, { useState } from 'react';
import axios from 'axios';
import { Upload, Send, Sparkles, ShieldCheck, Mail, FileText, CheckCircle } from 'lucide-react';
import './App.css';

const API_BASE = 'http://localhost:5000/api';

function App() {
  const [files, setFiles] = useState([]);
  const [recipients, setRecipients] = useState([]);
  const [subject, setSubject] = useState('');
  const [aiPrompt, setAiPrompt] = useState('');
  const [content, setContent] = useState('');
  const [loading, setLoading] = useState(false);
  const [showOtp, setShowOtp] = useState(false);
  const [otp, setOtp] = useState('');
  const [status, setStatus] = useState('');

  const handleFileUpload = async (e) => {
    const uploadedFiles = Array.from(e.target.files);
    setFiles(uploadedFiles);
    
    const formData = new FormData();
    uploadedFiles.forEach(file => formData.append('files', file));
    
    setLoading(true);
    try {
      const res = await axios.post(`${API_BASE}/extract`, formData);
      setRecipients(res.data.emails);
      setStatus(`Extracted ${res.data.emails.length} recipients`);
    } catch (err) {
      console.error(err);
      setStatus('Failed to extract emails');
    } finally {
      setLoading(false);
    }
  };

  const generateWithAI = async () => {
    if (!aiPrompt) return;
    setLoading(true);
    try {
      const res = await axios.post(`${API_BASE}/generate-content`, { prompt: aiPrompt });
      setContent(res.data.content);
      setStatus('Content generated by AI Agent');
    } catch (err) {
      console.error(err);
      setStatus('AI Generation failed');
    } finally {
      setLoading(false);
    }
  };

  const requestOtp = async () => {
    if (recipients.length === 0 || !content || !subject) {
      alert('Please provide subject, content and recipients');
      return;
    }
    setLoading(true);
    try {
      await axios.post(`${API_BASE}/send-otp`, { email: 'rsudha0707@gmail.com' });
      setShowOtp(true);
      setStatus('OTP sent to your email');
    } catch (err) {
      console.error(err);
      setStatus('Failed to send OTP');
    } finally {
      setLoading(false);
    }
  };

  const verifyAndSend = async () => {
    setLoading(true);
    try {
      await axios.post(`${API_BASE}/send-bulk`, {
        senderEmail: 'rsudha0707@gmail.com',
        otp,
        recipients,
        subject,
        content
      });
      setShowOtp(false);
      setOtp('');
      setStatus('Campaign sent successfully!');
      alert('Emails sent to all recipients!');
    } catch (err) {
      console.error(err);
      setStatus('Verification failed or sending error');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="app-container">
      <header className="header">
        <h1>Digital Daak Portal</h1>
        <p>Intelligent Email Automation with AI & File Extraction</p>
        {status && <span className="status-badge">{status}</span>}
      </header>

      <div className="grid">
        {/* Left Side: Data & Files */}
        <div className="card">
          <div className="card-title">
            <FileText size={24} />
            Data Extraction
          </div>
          <div className="file-upload-zone" onClick={() => document.getElementById('fileInput').click()}>
            <Upload size={48} color="var(--primary)" style={{ marginBottom: '1rem' }} />
            <h3>Upload Company Files</h3>
            <p>Support for Excel, PDF, and Text files</p>
            <input 
              id="fileInput" 
              type="file" 
              multiple 
              onChange={handleFileUpload} 
              style={{ display: 'none' }}
            />
          </div>
          
          <div className="email-list">
            <div className="card-title" style={{ fontSize: '1rem', marginBottom: '0.5rem' }}>
              <CheckCircle size={18} />
              Recipients ({recipients.length})
            </div>
            {recipients.length > 0 ? (
              recipients.map((email, i) => (
                <div key={i} className="email-item">
                  {email}
                  <span style={{ color: 'var(--accent)' }}>Active</span>
                </div>
              ))
            ) : (
              <p style={{ color: 'var(--text-muted)', textAlign: 'center' }}>No recipients yet</p>
            )}
          </div>
        </div>

        {/* Right Side: AI & Content */}
        <div className="card">
          <div className="card-title">
            <Sparkles size={24} />
            AI Content Agent
          </div>
          
          <div className="input-group">
            <label>What should the AI write?</label>
            <textarea 
              rows="3" 
              placeholder="e.g. Write a professional introduction about our new service..."
              value={aiPrompt}
              onChange={(e) => setAiPrompt(e.target.value)}
            />
            <button 
              className="btn btn-secondary" 
              style={{ marginTop: '0.5rem', width: '100%' }}
              onClick={generateWithAI}
              disabled={loading}
            >
              <Sparkles size={18} />
              Generate Content
            </button>
          </div>

          <div className="input-group">
            <label>Subject</label>
            <input 
              type="text" 
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
              placeholder="Enter email subject"
            />
          </div>

          <div className="input-group">
            <label>Final Email Context</label>
            <textarea 
              rows="8" 
              value={content}
              onChange={(e) => setContent(e.target.value)}
              placeholder="Email body will appear here..."
            />
          </div>

          <button 
            className="btn" 
            style={{ width: '100%' }}
            onClick={requestOtp}
            disabled={loading || recipients.length === 0}
          >
            <Send size={18} />
            Send to All ({recipients.length})
          </button>
        </div>
      </div>

      {/* OTP Overlay */}
      {showOtp && (
        <div className="otp-overlay">
          <div className="otp-card">
            <ShieldCheck size={64} color="var(--accent)" style={{ marginBottom: '1rem' }} />
            <h2>Security Verification</h2>
            <p>An OTP has been sent to <strong>rsudha0707@gmail.com</strong>. Please enter it below to confirm mass mailing.</p>
            
            <div className="otp-inputs">
              <input 
                className="otp-input" 
                type="text" 
                maxLength="6"
                style={{ width: '200px' }}
                value={otp}
                onChange={(e) => setOtp(e.target.value)}
              />
            </div>

            <div style={{ display: 'flex', gap: '1rem' }}>
              <button className="btn btn-secondary" onClick={() => setShowOtp(false)}>Cancel</button>
              <button className="btn" onClick={verifyAndSend}>Verify & Send</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default App;
